name: Validate and test

on:
  pull_request:
  push:
    branches: [ main ]
    tags-ignore: [ v* ]

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-gradle:
    name: Gradle tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Gather version
        run: |-
          echo `git describe --tags | sed -e "s/v\(.*\)-\([0-9][0-9]*\).*/\\1-\\2-/"``git rev-parse HEAD | head -c8`-SNAPSHOT > ~/.version
          cat ~/.version

      - name: Cache local Gradle repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('plugin-tester-*/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish artifacts locally
        #sbt akka-grpc-codegen/publishM2 akka-grpc-scalapb-protoc-plugin/publishM2 +akka-grpc-runtime/publishM2
        run: |-
          cp .jvmopts-ghactions .jvmopts
          cd gradle-plugin
          ./gradlew clean publishToMavenLocal --console=plain --info --stacktrace
          find ~/.m2 | grep gradle

      - name: Test Gradle Java ${{ matrix.SCALA_VERSION }}
        run: |-
          cd plugin-tester-java
          ./gradlew clean test --console=plain --info --stacktrace -Dakka.grpc.project.version=$(cat ~/.version | sed -e s/-SNAPSHOT//)

      - name: Stop Gradle Daemon
        # as suggested in https://github.com/actions/cache/blob/main/examples.md#java---gradle
        if: always()
        run: cd plugin-tester-scala; ./gradlew --stop
